using NUnit.Framework;
using OpenQA.Selenium;

namespace Wordpress
{
    [TestFixture]
    public class TitlesEducation : Base
    {
        
        [Test]
        [TestCase(EducationLinks.forex_education1, "Что такое стартовый капитал Форекс и какой он должен быть | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education2, "Форекс или фондовый рынок: что лучше выбрать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education3, "Торговый план Форекс: как его составить | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education4, "Основные валютные пары Форекс: какими лучше торговать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education5, "Экзотические валютные пары Форекс: плюсы и минусы торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education6, "Как торговать на Форекс без кредитного плеча: плюсы и минусы | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education7, "Как рассчитать Стоп Лосс и Тейк Профит на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education8, "Что такое спред на Форекс: значимость в трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education9, "Что такое Стоп Лосс (Stop Loss) и как его использовать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education10, "Что такое пипс (pips) на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education11, "Что такое лот Форекс и как его рассчитать вручную | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education12, "Кредитное плечо на рынке Форекс: что это и как работает | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education13, "Что такое проскальзывание на Форекс и как этого избежать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education14, "Как использовать ордер Take Profit в торговле на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education15, "Что такое гэп в трейдинге — полное руководство и стратегия | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education16, "Ночная торговля на Форекс: особенности ночного рынка | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education17, "Что такое CFD контракты и как ими торговать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education18, "Форекс мошенники: как не попасться и предотвратить обман | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education19, "Паритет покупательной способности валют на Форекс: как использовать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education20, "Торговые сессии Форекс — график работы рынка Forex | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education21, "Дейтрейдинг на рынке Форекс для начинающих: полное руководство | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education22, "Как прогнозировать рынок Форекс и предугадывать тренд | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education23, "Как выбрать лучший симулятор торговли Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education24, "Демо счет Форекс: как открыть и его преимущества | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education25, "Что такое уровень Стоп Аут (Stop Out) на бирже Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education26, "Что такое маржа на рынке Форекс: уровень маржи и Margin Call | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education27, "Кто такие маркет мейкеры на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education28, "Ликвидность финансового рынка: что это и на что она влияет | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education29, "Отложенные ордера на Форекс: инструкция по применению | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education30, "Количественное смягчение: что это и для чего оно нужно | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education31, "Что такое своп (SWAP) на рынке Форекс и зачем он нужен | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform1, "Торговые платформы Форекс: как выбрать платформу для торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform2, "Лучшие программы для Волнового анализа Эллиота | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform3, "Лучшие программы для построения графиков Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform4, "Лучшая программа для прогнозирования рынка Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform5, "Лучшая мобильная торговая платформа Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform6, "Лучшая торговая платформа для CFD торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform7, "Самые лучшие форекс инструменты для трейдера | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_platform8, "Лучшие программы для автоматической торговли на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education32, "Фундаментальный анализ Форекс рынка — что это | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education33, "Полосы Боллинджера — что стоит знать о работе индикатора на Форекс рынке | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education34, "Индикатор Волны Эллиота — как используется в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education35, "Индикатор ZigZag — применение в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education36, "Индикатор балансового объема (On Balance Volume) в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education37, "Скользящие средние — применение на Форекс рынке | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education38, "Индикатор High-Low для торговли на Форекс рынке | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education39, "Технический анализ — введение для начинающих форекс трейдеров | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education40, "Индикатор MACD в Форекс торговле | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education41, "Индекс Относительной Бодрости (RVI) — индикатор Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education42, "Индикатор Индекс Силы Элдера (Elder’s Force Index) | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education43, "Что такое настроение рынка Форекс и как использовать в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education44, "Индикатор Стохастик для торговли на Форекс рынке | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education45, "Индикатор MFI — как использовать в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education46, "Индикатор Linear Regression для анализа Форекс рынка | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education47, "Русскоязычные форумы трейдеров | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education48, "Анализ рынка Форекс для трейдеров | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education49, "Японские свечи Форекс: как использовать трейдерам | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education50, "Понимание Форекс котировок: что такое прямая и обратная котировка валют | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education51, "Комиссия брокера на рынке Форекс — что это | TradeAllCrypto")]
        [TestCase(EducationLinks.investments1, "Как инвестировать в нефть — инвестиции в черное золото | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education52, "Что такое короткая позиция в Форекс трейдинге | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education53, "Торговля индексом Dow Jones (Доу Джонс) | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education54, "Что такое торговля фондовыми индексами на Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education55, "Что такое торговля фондовыми индексами на Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.investments2, "Что такое голубые фишки и как торговать голубыми фишками | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education56, "Торговля опционами: что это и как торговать CFD на опционы | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education57, "Как торговать парой Форекс Евро Доллар (EUR/USD) | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education58, "Торговля CFD на DAX30 — руководство для трейдеров | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education59, "Как торговать валютной парой Форекс USD/JPY | TradeAllCrypto")]     
        [TestCase(EducationLinks.forex_education60, "Торговля CFD и торговля фьючерсами: Различия и особенности контрактов | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education61, "Рубль на Форекс — перспективы и торговые стратегии | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education62, "Как торговать GBP/USD — особенности торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education63, "Как торговать индексом FTSE 100 | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education64, "Индекс S&P500 — как им торговать на Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education65, "Как использовать экономический календарь в трейдинге | TradeAllCrypto")]

        [TestCase(EducationLinks.forex_strategies1, "Скальпинг стратегии для торговли на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.trading_bots1, "Торговые роботы Форекс — как работают торговые боты Forex | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies2, "Свинг-трейдинг — стратегии и применение | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies3, "Торговая стратегия Снайпер для Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies4, "Что такое Price Action: как торговать по паттернам ценового действия | TradeAllCrypto")]
        [TestCase(EducationLinks.markets1, "Как торговать биткоинами: разбираемся в основах | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies5, "Как работать с торговыми графиками: советы для начинающих трейдеров | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education66, "Как выбрать брокера Forex и CFD | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education67, "Что такое волатильность валютных пар на рынке Форекс | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education68, "Основные виды брокеров Форекс — ECN, STP, ECN/STP | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education69, "Как торговать с помощью индикатора силы валют | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education70, "Что такое Биткоин простыми словами: суть Bitcoin | TradeAllCrypto")]
        [TestCase(EducationLinks.investments3, "Инвестиции в валюту: как оценить риски и выбирать валюту для вложения | TradeAllCrypto")]

        [TestCase(EducationLinks.forex_strategies6, "Краткосрочные торговые стратегии Форекс — примеры и описания | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education71, "Психология торговли на рынке Форекс — ключевой фактор трейдинга | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education72, "Самые успешные трейдеры мира — истории успеха | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education73, "Основные ошибки Форекс трейдеров в биржевой торговле | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education74, "Как стать успешным трейдером на Форекс бирже | TradeAllCrypto")]
        [TestCase(EducationLinks.investments4, "Уоррен Баффет — советы по инвестированию в фондовый рынок | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education75, "Финансовый рынок: структура и функции | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education76, "Что такое индикаторы Форекс (Forex Indicator) | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education77, "Что такое валютный рынок Форекс и как он работает | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education78, "Тенденции рынка Форекс: что такое тренд на рынке Forex | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education79, "Лучшие торговые индикаторы для скальпинга | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies7, "Стратегия Мартингейла на Форекс — как безопасно увеличить прибыль | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education80, "Индикаторы уровней поддержки и сопротивления для Форекс торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education81, "Корреляция валютных пар на Форекс — что это и как рассчитать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education82, "Индекс относительной силы RSI и как им пользоваться | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education83, "Трейдер Билл Вильямс и его индикаторы для Форекс торговли | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education84, "Индикатор Аллигатор и торговые стратегии Форекс с его использованием | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies8, "Парный трейдинг — что это и как его применять в Форекс торговле  | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_education85, "Овертрейдинг — что это и как его избежать | TradeAllCrypto")]
        [TestCase(EducationLinks.forex_strategies9, "Стратегия торговли на сетке ордеров Форекс | TradeAllCrypto")]


        public void CheckTitle(string Local, string expectedTitle)
        {
            driver.Url = Local;           
            Hel_per.Timeout();
            string actualTitle = driver.FindElement(By.CssSelector("head > title")).GetAttribute("text");
            Assert.AreEqual(expectedTitle, actualTitle);
        }
    }
}